### ISSUE TITLE
Unable to download any file

### ISSUE THREAD

**Issue by futanarink** [mbahArip/next-gdrive-index#48]
Here is the link of my config file
https://github.com/flicga9989/next-gdrive-index/blob/main/src/config/gIndex.config.ts

Here is the ss of folder sharing access
<img width="642" height="546" alt="Image" src="https://github.com/user-attachments/assets/73c77555-3302-4f29-9c1e-1aa33e361e9f" />

Link to my vercel app
https://next-gdrive-index-qrg2.vercel.app/

**Comment by futanarink** [comment]
Re deployed again and here are the logs

[17:16:31.781] Running build in Washington, D.C., USA (East) – iad1
[17:16:31.781] Build machine configuration: 2 cores, 8 GB
[17:16:31.805] Cloning github.com/flicga9989/next-gdrive-index (Branch: main, Commit: 04397f4)
[17:16:31.813] Skipping build cache, deployment was triggered without cache.
[17:16:32.162] Cloning completed: 356.000ms
[17:16:32.460] Running "vercel build"
[17:16:32.863] Vercel CLI 46.0.5
[17:16:33.197] Installing dependencies...
[17:16:33.237] bun install v1.2.21 (7c45ed97)
[17:16:33.264] Resolving dependencies
[17:16:33.306] Resolved, downloaded and extracted [2]
[17:16:40.954] Saved lockfile
[17:16:40.959] 
[17:16:40.960] + @tailwindcss/typography@0.5.15
[17:16:40.960] + @trivago/prettier-plugin-sort-imports@4.3.0
[17:16:40.960] + @types/cors@2.8.17
[17:16:40.960] + @types/eslint@8.56.12
[17:16:40.960] + @types/mime-types@2.1.4
[17:16:40.960] + @types/node@20.17.9
[17:16:40.961] + @types/nprogress@0.2.3
[17:16:40.961] + @types/react@18.3.14
[17:16:40.961] + @types/react-dom@18.3.3
[17:16:40.961] + @types/three@0.150.2
[17:16:40.961] + @typescript-eslint/eslint-plugin@8.18.0
[17:16:40.961] + @typescript-eslint/parser@8.18.0
[17:16:40.961] + autoprefixer@10.4.20
[17:16:40.961] + chalk@5.4.1
[17:16:40.961] + commander@13.1.0
[17:16:40.961] + encoding@0.1.13
[17:16:40.961] + eslint@8.57.1
[17:16:40.961] + eslint-config-next@15.0.4
[17:16:40.961] + ora@8.2.0
[17:16:40.961] + postcss@8.4.49
[17:16:40.961] + prettier@3.0.0
[17:16:40.961] + prettier-plugin-tailwindcss@0.5.12
[17:16:40.961] + prompts@2.4.2
[17:16:40.961] + tailwindcss@3.4.16
[17:16:40.961] + typescript@5.7.2
[17:16:40.961] + @hookform/resolvers@3.10.0
[17:16:40.962] + @oslojs/encoding@1.1.0
[17:16:40.962] + @radix-ui/react-accordion@1.2.3
[17:16:40.962] + @radix-ui/react-alert-dialog@1.1.2
[17:16:40.962] + @radix-ui/react-aspect-ratio@1.1.0
[17:16:40.962] + @radix-ui/react-avatar@1.1.1
[17:16:40.962] + @radix-ui/react-checkbox@1.1.3
[17:16:40.962] + @radix-ui/react-collapsible@1.1.1
[17:16:40.962] + @radix-ui/react-context-menu@2.2.4
[17:16:40.962] + @radix-ui/react-dialog@1.1.6
[17:16:40.962] + @radix-ui/react-dropdown-menu@2.1.2
[17:16:40.962] + @radix-ui/react-hover-card@1.1.2
[17:16:40.962] + @radix-ui/react-label@2.1.1
[17:16:40.962] + @radix-ui/react-menubar@1.1.2
[17:16:40.962] + @radix-ui/react-navigation-menu@1.2.1
[17:16:40.962] + @radix-ui/react-popover@1.1.2
[17:16:40.963] + @radix-ui/react-progress@1.1.0
[17:16:40.963] + @radix-ui/react-radio-group@1.2.1
[17:16:40.963] + @radix-ui/react-scroll-area@1.2.2
[17:16:40.963] + @radix-ui/react-select@2.1.2
[17:16:40.963] + @radix-ui/react-separator@1.1.2
[17:16:40.963] + @radix-ui/react-slider@1.2.1
[17:16:40.963] + @radix-ui/react-slot@1.1.2
[17:16:40.963] + @radix-ui/react-switch@1.1.2
[17:16:40.963] + @radix-ui/react-tabs@1.1.1
[17:16:40.963] + @radix-ui/react-toast@1.2.2
[17:16:40.963] + @radix-ui/react-toggle@1.1.0
[17:16:40.963] + @radix-ui/react-toggle-group@1.1.0
[17:16:40.963] + @radix-ui/react-tooltip@1.1.8
[17:16:40.963] + @tanstack/react-virtual@3.11.2
[17:16:40.964] + @vidstack/react@1.12.12
[17:16:40.964] + class-variance-authority@0.7.1
[17:16:40.964] + clsx@2.1.1
[17:16:40.964] + cmdk@1.0.0
[17:16:40.964] + embla-carousel-react@8.5.1
[17:16:40.972] + embla-carousel-wheel-gestures@8.0.1
[17:16:40.973] + fflate@0.8.2
[17:16:40.974] + framer-motion@11.13.3
[17:16:40.974] + googleapis@144.0.0
[17:16:40.975] + lucide-react@0.477.0
[17:16:40.986] + next@15.1.6
[17:16:40.987] + next-themes@0.4.4
[17:16:40.987] + nextjs-toploader@1.6.12
[17:16:40.987] + react-dom@18.3.1
[17:16:40.987] + react-hook-form@7.54.2
[17:16:40.988] + react-markdown@8.0.7
[17:16:40.988] + rehype-katex@6.0.3
[17:16:40.988] + rehype-prism-plus@1.6.3
[17:16:40.988] + rehype-raw@6.1.1
[17:16:40.988] + remark-breaks@4.0.0
[17:16:40.989] + remark-gfm@3.0.1
[17:16:40.992] + remark-math@5.1.1
[17:16:40.992] + remark-slug@7.0.1
[17:16:40.993] + remark-toc@8.0.1
[17:16:40.994] + server-only@0.0.1
[17:16:40.994] + sonner@1.7.1
[17:16:40.994] + tailwind-merge@2.5.5
[17:16:40.994] + tailwindcss-animate@1.0.7
[17:16:40.995] + vaul@1.1.1
[17:16:40.995] + zod@3.24.1
[17:16:40.995] 
[17:16:40.996] 741 packages installed [7.74s]
[17:16:41.009] Detected Next.js version: 15.1.6
[17:16:41.012] Running "bun run build"
[17:16:41.015] $ next build
[17:16:42.599] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:16:42.600] This information is used to shape Next.js' roadmap and prioritize features.
[17:16:42.600] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:16:42.601] https://nextjs.org/telemetry
[17:16:42.601] 
[17:16:42.663]    ▲ Next.js 15.1.6
[17:16:42.663] 
[17:16:42.728]    Creating an optimized production build ...
[17:17:44.245] Browserslist: browsers data (caniuse-lite) is 9 months old. Please run:
[17:17:44.246]   npx update-browserslist-db@latest
[17:17:44.246]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[17:18:02.407]  ✓ Compiled successfully
[17:18:02.414]    Linting and checking validity of types ...
[17:18:48.763]    Collecting page data ...
[17:18:55.059]    Generating static pages (0/6) ...
[17:19:05.993]    Generating static pages (1/6) 
[17:19:05.994]    Generating static pages (2/6) 
[17:19:05.995]    Generating static pages (4/6) 
[17:19:05.995]  ✓ Generating static pages (6/6)
[17:19:10.044]    Finalizing page optimization ...
[17:19:10.052]    Collecting build traces ...
[17:19:17.899] 
[17:19:17.906] Route (app)                              Size     First Load JS
[17:19:17.907] ┌ ƒ /                                    266 B           798 kB
[17:19:17.907] ├ ƒ /_not-found                          164 B           106 kB
[17:19:17.907] ├ ƒ /[...rest]                           24.5 kB         904 kB
[17:19:17.907] ├ ƒ /api/download/[...rest]              164 B           106 kB
[17:19:17.907] ├ ƒ /api/internal/check                  164 B           106 kB
[17:19:17.907] ├ ƒ /api/internal/encrypt                164 B           106 kB
[17:19:17.907] ├ ƒ /api/og/[encryptedId]                164 B           106 kB
[17:19:17.908] ├ ƒ /api/preview/[encryptedId]           164 B           106 kB
[17:19:17.908] ├ ƒ /api/raw/[...rest]                   164 B           106 kB
[17:19:17.908] ├ ƒ /api/thumb/[encryptedId]             164 B           106 kB
[17:19:17.908] ├ ○ /ngdi-internal                       1.8 kB          650 kB
[17:19:17.908] ├ ○ /ngdi-internal/configurator          249 B           931 kB
[17:19:17.908] ├ ○ /ngdi-internal/deploy                249 B           931 kB
[17:19:17.908] └ ƒ /ngdi-internal/embed/[...rest]       281 B           931 kB
[17:19:17.908] + First Load JS shared by all            106 kB
[17:19:17.908]   ├ chunks/1517-a1fd0a49ac49b4ad.js      50.7 kB
[17:19:17.908]   ├ chunks/4bd1b696-3c23527ebc8df428.js  53 kB
[17:19:17.909]   └ other shared chunks (total)          2.23 kB
[17:19:17.909] 
[17:19:17.909] 
[17:19:17.909] ƒ Middleware                             32.3 kB
[17:19:17.909] 
[17:19:17.910] ○  (Static)   prerendered as static content
[17:19:17.910] ƒ  (Dynamic)  server-rendered on demand
[17:19:17.910] 
[17:19:18.192] Traced Next.js server files in: 134.615ms
[17:19:18.531] Created all serverless functions in: 333.529ms
[17:19:18.603] Collected static files (public/, static/, .next/static): 13.298ms
[17:19:18.741] Build Completed in /vercel/output [3m]
[17:19:18.922] Deploying outputs...
[17:19:29.273] Deployment completed
[17:19:30.328] Creating build cache...
[17:19:51.253] Created build cache: 20.925s
[17:19:51.255] Uploading build cache [243.64 MB]
[17:19:54.502] Build cache uploaded: 3.247s


Runtime logs are also attached here

[logs_result.json](https://github.com/user-attachments/files/22024258/logs_result.json)

**Comment by futanarink** [comment]
I just checked this file [next-gdrive-index](https://github.com/flicga9989/next-gdrive-index/tree/main)/[src](https://github.com/flicga9989/next-gdrive-index/tree/main/src)/[components](https://github.com/flicga9989/next-gdrive-index/tree/main/src/components)/[explorer](https://github.com/flicga9989/next-gdrive-index/tree/main/src/components/explorer)
/FileItem.tsx

And there is no definition of download function, line 94

`const onDownload = useCallback(async () => {
    void 0;
  }, []);`

**Comment by mbahArip** [comment]
Fix pushed #49 
Can you try, and confirm?

**Comment by futanarink** [comment]
Still not working. When i click download in context menu

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/88485c74-b188-4c4f-876e-b32370e10f87" />

When I open the image to preview

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d12729ca-865f-4997-af61-c86c274a5c40" />

Logs from vercel
[

[logs_result (1).json](https://github.com/user-attachments/files/22059826/logs_result.1.json)

](url)

**Comment by shing-yu** [comment]
any updates?
all my files shows "Can't find"

**Comment by shing-yu** [comment]
Oh, I know why, you need to explicitly give the service account (***@***.gserviceaccount.com) "viewer" permission on the Google Drive page.
